### ISSUE TITLE
提一个小问题，方便不方便告知navigation问题

### ISSUE THREAD

**Issue by colmugx** [ahonn/v2exRN#1]
MenuView.js 52:29

navigation 是指向哪里，或者是哪个包已有定义？

希望告知，谢谢。

**Comment by ahonn** [comment]
指向 `android/app/src/main/res/drawable-xxxx` 下的 navigation.png，例如：https://github.com/ahonn/v2exRN/blob/master/android/app/src/main/res/drawable-xhdpi/navigation.png
